name: scirnaseq
channels:
  - conda-forge
  - bioconda
dependencies:
  - cutadapt>=4.5
  - jupyter
  - matplotlib
  - pandas
  - openpyxl
  - star
  - quarto
  - snakemake-minimal
  - snakemake-executor-plugin-slurm
  - tinyalign
  - scipy
  - pysam
  - samtools
  - r-optparse
  - r-seurat
